{
    "Paginass":{
    "selector": "li.andes-pagination__page-count",
        "type": "text"
},
    "items": {
    "multi":true,
        "selector":"li.ui-search-layout__item",
        "type":"object",
        "children":{
        "es_proyecto":{
            "selector":"span.ui-search-styled-label.ui-search-item__highlight-label__text:nth-child(1)",
                "type":"text"
        },
        "es_desde":{
            "selector":"div.ui-search-price__front-price",
                "type":"text"
        },
        "moneda":{
            "selector":"span.price-tag-symbol",
                "type":"text"
        },
        "valor":{
            "selector":"span.price-tag-fraction",
                "type":"text"
        },
        "rango_m2_utiles":{
            "selector":"li.ui-search-card-attributes__attribute:nth-child(1)",
                "type":"text"
        },
        "rango_dormitorios":{
            "selector":"li.ui-search-card-attributes__attribute:nth-child(2)",
                "type":"text"
        },
        "rango_baÃ±os":{
            "selector":"li.ui-search-card-attributes__attribute:nth-child(3)",
                "type":"text"
        },
        "es_depto_venta":{
            "selector":"span.ui-search-item__group__element.ui-search-item__subtitle",
                "type":"text"
        },
        "ubicacion":{
            "selector":"p.ui-search-item__group__element.ui-search-item__location",
                "type":"text"
        }
    }
}
}